### ISSUE TITLE
Speed up with TopK Transformer / MoE

### ISSUE THREAD

**Issue by kiucho** [RobertCsordas/moe#1]
Thanks for sharing great research.

Is there actual speed up with TopK transformer and MoE?

**Comment by RobertCsordas** [comment]
Thanks for the interest!

With MoE yes (especially with the Triton kernel), with TopK, no. However, we haven't even tried hard for TopK because of the inherent limitations discussed in the paper. We use a naive implementation. For MoE, Fig 2 shows timing benchmarks while maintaining the d_model - 4d_model - d_model shape for the MLP, and in the Appendix Fig 8 - 11 shows timing benchmarks for scaling along different axis. These measure the total forward-backward time for the layer and they accurately reflect the effect when used in the full Transformer model. A quick link to the paper: https://arxiv.org/abs/2310.10837
